[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  autocmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'deton/jasegment.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  let g:asyncomplete_smart_completion = 1
  set completeopt-=preview

  inoremap <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"
  imap <c-space> <Plug>(asyncomplete_force_refresh)
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'
hook_add = '''
  call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
  \ 'name': 'buffer',
  \ 'whitelist': ['*'],
  \ 'completor': function('asyncomplete#sources#buffer#completor'),
  \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
hook_add = '''
  au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
  \ 'name': 'file',
  \ 'whitelist': ['*'],
  \ 'priority': 10,
  \ 'completor': function('asyncomplete#sources#file#completor')
  \ }))
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  if executable('solargraph')
    au User lsp_setup call lsp#register_server({
    \ 'name': 'solargraph',
    \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
    \ 'initialization_options': {"diagnostics": "true"},
    \ 'whitelist': ['ruby'],
    \ })
  endif

  if executable('pyls')
    au User lsp_setup call lsp#register_server({
    \ 'name': 'pyls',
    \ 'cmd': {server_info->['pyls']},
    \ 'whitelist': ['python'],
    \ })
  endif

  if executable('javascript-typescript-stdio')
    au User lsp_setup call lsp#register_server({
    \ 'name': 'javascript-typescript-langserver',
    \ 'cmd': {server_info->[&shell, &shellcmdflag, 'javascript-typescript-stdio']},
    \ 'whitelist': ['javascript', 'typescript', 'javascript.jsx'],
    \ })
  endif
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_linters = {
  \ 'ruby': ['rubocop'],
  \ 'python': ['flake8'],
  \ 'javascript': ['standard'],
  \ 'sh': ['shell'],
  \ }
'''

[[plugins]]
repo = 'othree/yajs.vim'
