# インデントガイドを表示
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=238 guibg=#3b4261
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=236 guibg=#2b3047
'''

# 括弧の補完
[[plugins]]
repo = 'cohama/lexima.vim'

# JavaScriptのsyntax highlight
[[plugins]]
repo = 'othree/yajs.vim'

# TypeScriptのsyntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'

# toml
[[plugins]]
repo = 'cespare/vim-toml'

# Markdownプレビュー
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'
hook_add = '''
let g:mkdp_auto_close = 0
'''

# 選択範囲内のMarkdownのテーブルを整形
[[plugins]]
repo = 'mattn/vim-maketable'

# LSPを利用してシンボル等をサイドバーで表示
[[plugins]]
repo = 'liuchengxu/vista.vim'
depends = 'coc.nvim'
hook_add = '''
  let g:vista_icon_indent = ["▸ ", ""]
  let g:vista_default_executive = 'coc'
  nnoremap <leader>o :Vista!!<CR>
'''

# Vim上からバッファ内のソースコード実行
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nnoremap Q :QuickRun<CR>
'''

# コードブロック内の言語に応じてfiletypeを変更する
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# vim-precious依存プラグイン
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Terraformのsyntax highlightなど
[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
let g:terraform_fmt_on_save = 1
'''

# Tree sitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
on_event = 'BufRead'
lua_post_source = '''
  require'nvim-treesitter.configs'.setup {
    ensure_installed = {
      "python",
      "ruby",
      "go",
      "dockerfile",
      "javascript",
      "typescript",
      "bash",
      "hcl",
      "terraform",
      "toml",
      "json",
      "yaml",
      "vimdoc"
    },
    highlight = {
      enable = true,
      disable = {
        "bash",
        "terraform"
      }
    }
  }
'''
hook_add = '''
  set foldmethod=expr
  set foldexpr=nvim_treesitter#foldexpr()
  set nofoldenable
'''
