# プラグインマネージャ本体
[[plugins]]
repo = 'Shougo/dein.vim'

# プロセス非同期実行用プラグイン
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# カラースキーム
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  autocmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

# 日本語の文節単位で移動できるようにする
[[plugins]]
repo = 'deton/jasegment.vim'

# ステータスラインカスタマイズ
[[plugins]]
repo = 'itchyny/lightline.vim'

# Vim上からバッファ内のソースコード実行
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nnoremap Q :QuickRun<CR>
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_linters = {
  \ 'ruby': ['rubocop'],
  \ 'python': ['flake8'],
  \ 'javascript': ['standard'],
  \ 'json': ['jsonlint'],
  \ 'sh': ['shell'],
  \ }

  let g:ale_enabled = 0
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_insert_leave = 1
  let g:ale_sign_column_always = 1
  let g:ale_keep_list_window_open = 1
  let g:ale_open_list = 1
  let g:ale_list_window_size = 5
'''

# 検索位置(検索ヒット数)を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
'''
hook_source = '''
  set statusline=%{anzu#search_status()}
'''

# Vim上からGit操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# Git logビューワ
[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
hook_add = '''
  let g:lightline = {}
  let g:lightline.component_expand = {
  \  'linter_checking': 'lightline#ale#checking',
  \  'linter_warnings': 'lightline#ale#warnings',
  \  'linter_errors': 'lightline#ale#errors',
  \  'linter_ok': 'lightline#ale#ok',
  \ }
  let g:lightline.component_type = {
  \ 'linter_checking': 'left',
  \ 'linter_warnings': 'warning',
  \ 'linter_errors': 'error',
  \ 'linter_ok': 'left',
  \ }
  let g:lightline.component_function = {
  \ 'gitbranch': 'FugitiveHead'
  \ }
  let g:lightline.active = {
  \ 'left': [ [ 'mode', 'paste' ],
  \           [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
  \ 'right': [ [ 'lineinfo' ],
  \            [ 'percent' ],
  \            [ 'fileformat', 'fileencoding', 'filetype' ],
  \            [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ] }
'''

# ウィンドウサイズ変更支援
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
   let g:winresizer_start_key = '<leader>w'
   let g:winresizer_gui_start_key = '<leader>W'
'''

# コードブロック内の言語に応じてfiletypeを変更する
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# vim-precious依存プラグイン
[[plugins]]
repo = 'Shougo/context_filetype.vim'
