# nvim-treeのアイコンフォント対応
[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

# ファイラ本体
[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
lua_add = '''
  -- netrwの無効化
  vim.g.loaded_netrw = 1
  vim.g.loaded_netrwPlugin = 1

  -- nvim-treeの設定
  require("nvim-tree").setup({
    -- タブ間でnvim-treeの状態を同期
    tab = {
      sync = {
        open = true,
        close = true
      }
    },
    -- gitignore対象のファイルをデフォルトで表示
    git = {
      ignore = false
    },
    -- dotfileをデフォルトで非表示、.gitignoreだけは常に表示する
    filters = {
      dotfiles = true,
      exclude = {".gitignore"}
    }
  })
'''
hook_add = '''
  nmap <silent> <leader>e :NvimTreeToggle<CR>
'''
depends = ['nvim-web-devicons']
